### ISSUE TITLE
Problem with episode cast

### ISSUE THREAD

**Issue by roidy** [jurialmunkey/script.module.infotagger#5]
Not sure weather this is an infotagger or TMDB Helper issue so I'll just post here.

I'm attaching the cast to an episode using `info_tag.set_cast(cast)` this works fine, Kodi's `ListItem.Cast` is filled in correctly however your TMDB service monitor will not return the individual cast members:-

`ListItem.Property(Cast.1.Name)` and so on.

It works fine for DBType Movie and TVShow but fails for Episodes. Same Issue with Writer, Director and Creator.

**Comment by jurialmunkey** [comment]
TMDbHelper service doesn't return information from the ListItem. It returns information from an online lookup. 

Whatever you set to cast for the listitem has no relevance for TMDbHelper service as it doesn't use that information.

**Comment by roidy** [comment]
Ok thanks, so what property do I need to set on my ListItem to get the lookup to happen?

**Comment by jurialmunkey** [comment]
For episodes you need to set mediatype to episode (ie listitem.dbtype).

Then the lookup is based upon listitem.uniqueid(tvshow.tmdb) and season and episode number

If you don't have tvshow.tmdb id then it fallsback to uniqueid(tmdb) which should be ID of episode.

Failing that it fallsback to tvshowtitle and uses year to find first match tvshow which started on or before that year (because episodes can have years after premiere year).
